---
- name: collect device facts and running configs
  hosts: "{{ hosts | default('all') | lower }}"
  gather_facts: yes
  connection: "{{ ansible_connection | default(network_cli) }}"

  roles:
    - role: network_facts

  tasks:
  
    - debug:
        msg: "Device {{ inventory_hostname }} is type {{ ansible_network_os }}"

  #- name: print ansible facts
  #  debug:
  #    var: ansible_facts

  #- name: print hostvars
  #  debug:
  #    var: hostvars
  
