---
- name: backup current device config
  ios_config:
    backup: yes
    backup_options:
      filename: "{{ ansible_network_os }}-{{ inventory_hostname }}.cfg"
      dir_path: /var/tmp/backup/

- name: push new device config
  ios_config:
    src: /var/tmp/config/ios.j2
