---
- hosts: localhost
  connection: local
  
  tasks:
  
    # This will generate a password that's 16-characters in length and contains a minimum of 1 lowercase, uppercase, number, and special characters.
    # The 'override_special' option will allow you to specify the special characters to be used.
    # Credit to Tanay Shah: https://github.com/tanay1307shah
    
    - name: generate a random password
      ansible.builtin.set_fact:
        random_password: "{{ lookup('community.general.random_string',length=16,min_lower=1, min_upper=1, min_special=1, min_numeric=1,override_special=['!','#']) }}”
    
    - name: print out random password
      ansible.builtin.debug:
        var: random_password
