# author: Tanay Shah
# source: https://github.com/tanay1307shah
# desc: This will generate a password that's 16-characters in length, and which contain a minimum of 1 each for lowercase, uppercase, numeral, and special characters. The 'override_special' option will allow you to define which special characters are to be used.
---
- hosts: localhost

  tasks:
    
    - name: generate a random password
      ansible.builtin.set_fact:
        random_password: "{{ lookup('community.general.random_string',length=16,min_lower=1,min_upper=1,min_special=1,min_numeric=1,override_special=['!','#']) }}”
    
    - name: print random password
      ansible.builtin.debug:
        var: random_password
