- name: Configure VLANs 
  nxos_vlans:
    config:
      - vlan_id: "{{ item['vlan_id'] }}"
        name: "{{ item['vlan_name'] }}"
    state: merged 
  when: vlan_config is defined
  loop: "{{ vlan_config }}"

- name: Configure Interface Settings
  nxos_interfaces:
    config:
      - name: "{{ item['interface'] }}"
        description: "{{ item['description'] }}"
        enabled: "{{ item['enabled'] }}"
        mode: "{% if 'ip_address' in item %}layer3{% else %}layer2{% endif %}"
    state: replaced
  loop: "{{ interface_config }}"
  when: (interface_config is defined and (item['enabled'] == True))

- nxos_bfd_global:
    echo_interface: "{{ item['interface'] }}"
    echo_rx_interval: 300
    interval:
      tx: 300
      min_rx: 300
      multiplier: 3
  loop: "{{ interface_config }}"
  when: (interface_config is defined and (item['enabled'] == True))

- name: Configure Port Channels
  nxos_lag_interfaces:
    config:
      - name: "{{ item['interface'] }}"
        members: "{{ item['members'] }}"
    state: replaced
  loop: "{{ interface_config }}"
  when: port-channel in item['interface']

- name: Configure Prefix Lists
  nxos_config:
    src: prefix-list/AWS-AF-DEV-DATABRICKS.j2
