---

- name: Include host variables file
  include_vars: "{{ item }}"
  with_first_found: 
    - "{{ site }}/{{ zone }}/{{ inventory_hostname }}.yml"
    - default.yml
    
- name: "Include {{ ansible_network_os }} tasks"
  include_tasks: "{{ ansible_network_os }}.yml"

#- name: Build VPC Configuration
#  include_tasks: "{{ ansible_network_os }}_vpc.yml"
#  when: 
#    - ansible_network_os == 'nxos'
#  tags: VPC
#
#- name: "Include {{ ansible_network_os }} shutdown tasks"
#  include_tasks: "{{ ansible_network_os }}_shutdown.yml"
#